In [2]:
import pandas as pd
import numpy as np

Zad 1

In [73]:
df=pd.read_csv('/Users/michalluniewski/Documents/PAD/04_PAD/Zadanie domowe/Zadanie_1.csv', sep=';')
df.values

array([[3.600000e+01, 2.700000e+01, 7.100000e+01, 8.100000e+00,
        3.340000e+00, 1.140000e+01, 8.150000e+01, 3.243000e+03,
        8.800000e+00, 4.260000e+01, 1.170000e+01, 2.100000e+01,
                 nan, 5.900000e+01, 5.900000e+01, 9.218700e+02],
       [3.500000e+01, 2.300000e+01, 7.200000e+01, 1.110000e+01,
        3.140000e+00, 1.100000e+01, 7.880000e+01, 4.281000e+03,
        3.600000e+00, 5.070000e+01, 1.440000e+01, 8.000000e+00,
        1.000000e+01, 3.900000e+01, 5.700000e+01, 9.978750e+02],
       [4.400000e+01, 2.900000e+01, 7.400000e+01, 1.040000e+01,
        3.210000e+00, 9.800000e+00, 8.160000e+01, 4.260000e+03,
        8.000000e-01, 3.940000e+01,          nan, 6.000000e+00,
        6.000000e+00, 3.300000e+01, 5.400000e+01, 9.623540e+02],
       [4.700000e+01, 4.500000e+01, 7.900000e+01, 6.500000e+00,
        3.410000e+00, 1.110000e+01, 7.750000e+01, 3.125000e+03,
        2.710000e+01, 5.020000e+01, 2.060000e+01, 1.800000e+01,
        8.000000e+00, 2.400000e+01, 5

Zad 1A

In [74]:
df.size

960

Zad 1B

In [75]:
numOfRows = np.size(df, 0)
print(numOfRows)
numOfColumns = np.size(df, 1)
print(numOfColumns)


60
16


Zad 1C

In [76]:
print(np.mean(df, axis=0))
print(np.median(df, axis=0))
print(np.median(df, axis=0))

x1       37.464286
x2       35.368421
x3       74.644068
x4        8.798333
x5        3.280847
x6       10.971186
x7       80.837288
x8     3876.050000
x9       11.925424
x10      46.073333
x11      14.406780
x12      38.758621
x13      22.982759
x14      51.508772
x15      57.533333
Y       940.358433
dtype: float64
[     nan      nan      nan    9.         nan      nan      nan 3567.
      nan   45.5        nan      nan      nan      nan   57.     943.683]
[     nan      nan      nan    9.         nan      nan      nan 3567.
      nan   45.5        nan      nan      nan      nan   57.     943.683]


Zad 1D

In [77]:
np.count_nonzero(np.isnan(df))

20

In [78]:
df_without_nan = np.nan_to_num(df)
df_without_nan

array([[3.600000e+01, 2.700000e+01, 7.100000e+01, 8.100000e+00,
        3.340000e+00, 1.140000e+01, 8.150000e+01, 3.243000e+03,
        8.800000e+00, 4.260000e+01, 1.170000e+01, 2.100000e+01,
        0.000000e+00, 5.900000e+01, 5.900000e+01, 9.218700e+02],
       [3.500000e+01, 2.300000e+01, 7.200000e+01, 1.110000e+01,
        3.140000e+00, 1.100000e+01, 7.880000e+01, 4.281000e+03,
        3.600000e+00, 5.070000e+01, 1.440000e+01, 8.000000e+00,
        1.000000e+01, 3.900000e+01, 5.700000e+01, 9.978750e+02],
       [4.400000e+01, 2.900000e+01, 7.400000e+01, 1.040000e+01,
        3.210000e+00, 9.800000e+00, 8.160000e+01, 4.260000e+03,
        8.000000e-01, 3.940000e+01, 0.000000e+00, 6.000000e+00,
        6.000000e+00, 3.300000e+01, 5.400000e+01, 9.623540e+02],
       [4.700000e+01, 4.500000e+01, 7.900000e+01, 6.500000e+00,
        3.410000e+00, 1.110000e+01, 7.750000e+01, 3.125000e+03,
        2.710000e+01, 5.020000e+01, 2.060000e+01, 1.800000e+01,
        8.000000e+00, 2.400000e+01, 5

In [79]:
print(np.mean(df_without_nan, axis=0))
print(np.median(df_without_nan, axis=0))
print(np.median(df_without_nan, axis=0))

[3.49666667e+01 3.36000000e+01 7.34000000e+01 8.79833333e+00
 3.22616667e+00 1.07883333e+01 7.94900000e+01 3.87605000e+03
 1.17266667e+01 4.60733333e+01 1.41666667e+01 3.74666667e+01
 2.22166667e+01 4.89333333e+01 5.75333333e+01 9.40358433e+02]
[3.70000e+01 3.15000e+01 7.40000e+01 9.00000e+00 3.27500e+00 1.10000e+01
 8.08500e+01 3.56700e+03 1.04000e+01 4.55000e+01 1.32000e+01 1.40000e+01
 8.50000e+00 2.65000e+01 5.70000e+01 9.43683e+02]
[3.70000e+01 3.15000e+01 7.40000e+01 9.00000e+00 3.27500e+00 1.10000e+01
 8.08500e+01 3.56700e+03 1.04000e+01 4.55000e+01 1.32000e+01 1.40000e+01
 8.50000e+00 2.65000e+01 5.70000e+01 9.43683e+02]


Zad 2

In [80]:
df2 = np.loadtxt('/Users/michalluniewski/Documents/PAD/04_PAD/Zadanie domowe/Zadanie_2.csv', delimiter=';')
df2

array([[  1.,   2.,  15., -59.,   9.,   3.,  75.,   6.,   7.,   1.],
       [  0.,   5.,   0.,   4.,   6.,  16.,  44.,   7.,   1.,   1.],
       [  7.,  14.,   3., -10.,   9.,  15.,  73.,   8.,   2.,   9.],
       [  1.,   5.,  15., -54.,   5.,  15.,  35.,   8.,   6.,   4.],
       [  0.,   8.,   5., -18.,   7.,  16.,  91.,   6.,   7.,   9.],
       [  7.,  18.,  23., -90.,   4.,   8.,  31.,   0.,   1.,   7.],
       [  2.,   8.,  20., -72.,   4.,   1.,  91.,   9.,   4.,   4.],
       [  4.,  12.,  18., -65.,   6.,   9.,  76.,   4.,   9.,   9.],
       [  7.,  15.,  13., -52.,   5.,   7.,  54.,   2.,   7.,   0.],
       [  2.,   9.,  15., -56.,   6.,   1.,  98.,   4.,   8.,   4.]])

Zad 2A

In [81]:
from numpy import linalg as LA

In [82]:
w, v = LA.eig(df2)
print(f'Wartości {w}')
print(f'Wektory {v}')


Wartości [104.34960192 +0.j         -23.35660516+18.84992811j
 -23.35660516-18.84992811j  15.92989017 +0.j
  -4.99456452 +0.j           0.35205717 +5.80125175j
   0.35205717 -5.80125175j  -1.03383491 +0.j
   3.87900166 +1.42651533j   3.87900166 -1.42651533j]
Wektory [[-0.29000475+0.j         -0.07545445+0.07743149j -0.07545445-0.07743149j
  -0.03544485+0.j          0.42681634+0.j         -0.22172831-0.29869259j
  -0.22172831+0.29869259j  0.41343726+0.j         -0.28670255+0.21891569j
  -0.28670255-0.21891569j]
 [-0.24163153+0.j          0.41229621+0.09197324j  0.41229621-0.09197324j
   0.45873475+0.j         -0.27056206+0.j         -0.01331344+0.1422557j
  -0.01331344-0.1422557j  -0.31591047+0.j          0.41954481-0.10561864j
   0.41954481+0.10561864j]
 [-0.41060573+0.j          0.37509638-0.00960818j  0.37509638+0.00960818j
   0.64067986+0.j         -0.37967609+0.j         -0.60525232+0.j
  -0.60525232-0.j          0.6457768 +0.j          0.63631555+0.j
   0.63631555-0.j        ]
 [-

Zad 2B

In [83]:
matrixinv = np.linalg.inv(df2)
matrixinv

array([[ 0.47461371,  0.13269253, -0.24726695, -0.82965177,  0.28250384,
        -0.17012825,  0.58274426,  0.83686705,  0.4146721 , -1.56942847],
       [-0.38032531, -0.11226789,  0.23216372,  0.58853747, -0.2508954 ,
         0.10174485, -0.40729564, -0.58325689, -0.2335154 ,  1.11832726],
       [ 0.13559662,  0.58950334, -0.24709855, -0.58789838, -0.30170699,
        -0.12721938,  0.23740295,  1.01003036, -0.02151387, -0.64590149],
       [ 0.01425207,  0.14570726, -0.04557569, -0.12721972, -0.08945184,
        -0.03756624,  0.03910376,  0.23606066, -0.01436771, -0.11345749],
       [-0.09473246,  0.01725249,  0.19145597,  0.32960274, -0.28626296,
         0.08348529, -0.37577603, -0.27295934, -0.25855803,  0.74691827],
       [ 0.16387032,  0.10075684, -0.15404907, -0.29794662,  0.16916877,
        -0.02827782,  0.20469921,  0.28036265,  0.15086178, -0.5882585 ],
       [ 0.04288003,  0.02246462, -0.0366803 , -0.09024915,  0.04322146,
        -0.01047861,  0.06167348,  0.07009721

Zad 3

In [70]:
dfa = np.loadtxt('/Users/michalluniewski/Documents/PAD/04_PAD/Zadanie domowe/Zadanie_3_macierz_A.csv', delimiter=',')
dfb = np.loadtxt('/Users/michalluniewski/Documents/PAD/04_PAD/Zadanie domowe/Zadanie_3_macierz_B.csv', delimiter=',')
dfa, dfb

(array([[2., 2., 3.],
        [1., 0., 4.],
        [6., 9., 7.]]),
 array([[ 1.,  5.,  2.],
        [ 6.,  6.,  4.],
        [ 1., 10.,  7.],
        [ 5.,  8.,  2.],
        [ 3.,  0.,  6.]]))

In [72]:
dfa.shape, dfb.shape

((3, 3), (5, 3))

Zad 4

In [40]:
df4 = pd.read_csv('/Users/michalluniewski/Documents/PAD/04_PAD/Zadanie domowe/Zadanie_4.csv', sep=';', usecols=[0,1,2,3,])
df4.head(5)

DateTime  DoctorID Type    City
0  16.03.2020 12:00         1   GP  Warsaw
1  16.03.2020 12:01         1   GP  Warsaw
2  16.03.2020 12:02         1   GP  Warsaw
3  16.03.2020 12:03         1   GP  Warsaw
4  16.03.2020 12:04         1   GP  Warsaw

In [55]:
df4["Date"] = pd.to_datetime(df4['DateTime']).dt.date
df4["Time"] = pd.to_datetime(df4["DateTime"]).dt.time
df4.head(5)

DateTime  DoctorID Type    City       Dates     Times        Date  \
0  16.03.2020 12:00         1   GP  Warsaw  2020-03-16  12:00:00  2020-03-16   
1  16.03.2020 12:01         1   GP  Warsaw  2020-03-16  12:01:00  2020-03-16   
2  16.03.2020 12:02         1   GP  Warsaw  2020-03-16  12:02:00  2020-03-16   
3  16.03.2020 12:03         1   GP  Warsaw  2020-03-16  12:03:00  2020-03-16   
4  16.03.2020 12:04         1   GP  Warsaw  2020-03-16  12:04:00  2020-03-16   

       Time  
0  12:00:00  
1  12:01:00  
2  12:02:00  
3  12:03:00  
4  12:04:00

In [65]:
df4_min = df4.groupby(['DoctorID','Date','City','Type']).agg({'Time':'min'})
df4_max = df4.groupby(['DoctorID','Date','City','Type']).agg({'Time':'max'})
df4_min.rename(columns={'Time':'The doctor takes from'},inplace=True)
df4_max.rename(columns={'Time':'The doctor admits to'},inplace=True)
df4_final = pd.concat([df4_min,df4_max], join='inner', axis = 1)
df4_final

The doctor takes from  \
DoctorID Date       City   Type                                  
1        2020-03-16 Warsaw GP                         12:00:00   
         2020-03-29 Warsaw GP                         14:00:00   
2        2020-03-16 Krakow GP                         12:00:00   
3        2020-03-22 Warsaw Sugreon                    08:01:00   
4        2020-10-04 Krakow Opthomologist              13:20:00   

                                         The doctor admits to  
DoctorID Date       City   Type                                
1        2020-03-16 Warsaw GP                        14:01:00  
         2020-03-29 Warsaw GP                        14:37:00  
2        2020-03-16 Krakow GP                        12:49:00  
3        2020-03-22 Warsaw Sugreon                   09:06:00  
4        2020-10-04 Krakow Opthomologist             13:34:00

In [66]:
df4_final.to_csv('out.csv')